; Generated by scripts/generate_holistic_argument_sexp.py
(holistic-argument
  (thesis "FUTON is a self-representing stack that links aspiration (devmaps), execution (missions), and evidence into an auditable argument for what to do next.")
  (devmaps
    (devmap :id futon0
      :summary "FUTON0 is the interface through which the system extends human capability. It monitors vitality, rhythm, and attention, making human state legible to the stack and stack state perceivable to the human. The human is not a component of the system; the system is an extension of the human."
      :missions (
        (mission :id M-emacs-cursor-peripheral :summary "Specifies a greenfield Emacs cursor/avatar peripheral with follow/observe/scout/pair modes; implementation has not started pending prerequisites.")
      ))
    (devmap :id futon1
      :summary "FUTON1 provides a deterministic, storage-oriented substrate that maintains a coherent graph of facts across sessions. It keeps Datascript (fast) and XTDB (persistent) in reproducible alignment so that the same world state appears reliably across restarts and environments. It exposes a minimal CLI and HTTP surface for ingesting text, inspecting entities and relations, and emitting stable summaries—such as focus headers—that downstream code can depend on without embedding persistence or orchestration logic."
      :missions ())
    (devmap :id futon2
      :summary "FUTON2 provides a narratable Active Inference engine whose ants are first demonstrators for AIF agent species. The same engine powers futon3 fulab agents and may drive futon5 MetaCA simulations—making FUTON2 the shared AIF substrate that turns insight into kinetic practice across the stack."
      :missions ())
    (devmap :id futon3
      :summary "FUTON3 turns messy activity into organised knowledge by checking work against shared patterns and producing auditable records that other futons can use to learn, improve, and act."
      :missions (
        (mission :id M-social-exotype :summary "Verified the social exotype plus composition extension so social/task/glacial diagrams can be validated as one composed system.")
        (mission :id M-peripheral-gauntlet :summary "Defines the 8-gate autonomous multi-agent gauntlet; mission is at ARGUE -> VERIFY with several gate demonstrations still pending.")
        (mission :id M-forum-refactor :summary "Refactors legacy forum code into the evidence-landscape architecture; Part I is ready while Parts II-IV remain blocked on dependencies.")
        (mission :id M-agency-unified-routing :summary "Unified Agency routing so Claude/Codex agents can be registered and invoked inside one JVM without split Drawbridge processes.")
        (mission :id M-psr-pur-mesh-peripheral :summary "Delivered the `:discipline` PSR/PUR mesh peripheral with explicit hop semantics; Gate A/B pass and Gate C infra complete.")
        (mission :id M-alfworld-pattern-discovery :summary "Ran iterative ALFWorld sessions and crystallized the results into 10 reusable `library/alfworld/*.flexiarg` patterns.")
        (mission :id M-sliding-blackboard :summary "Proposes Emacs sliding side-panels for extracted chat code blocks; design is captured but implementation has not started.")
        (mission :id M-mission-peripheral :summary "Implemented a general 9-phase mission cycle machine with obligation tracking, phase gates, and automatic evidence snapshots.")
        (mission :id M-mission-control :summary "Implemented the mission-control peripheral for cross-repo inventory, devmap coverage, portfolio review, and backfill as evidence.")
        (mission :id M-operational-readiness :summary "Shipped the overnight-readiness batch (8 issues, 4 gates) so unattended multi-agent operation is observable and recoverable.")
        (mission :id M-portfolio-inference :summary "Added the AIF-style portfolio inference layer on top of mission-control observation, including prediction-error and policy-selection framing.")
      ))
    (devmap :id futon3a
      :summary "FUTON3A is the pattern guidance and audit logging layer. It provides Portal (Drawbridge pattern retrieval from Futon1), Sidecar (append-only audit trail of selections/actions/evidence), and Compass (GFE-inspired alignment scoring). The 象 (xiang) metaphor: patterns backed by living memory, not just static files. Flexiarg is the serialization format; futon3a is the operational substrate."
      :missions ())
    (devmap :id futon4
      :summary "FUTON4 is a memory workspace where documents, design patterns, and annotations share a common editing environment, letting symbolic artefacts be edited, linked, and narrated in one continuous workspace."
      :missions (
        (mission :id M-evidence-viewer-refinements :summary "Upgraded the evidence viewer from debug table to operator console (live-tail controls, context cards, presets, theme alignment).")
        (mission :id M-self-representing-stack :summary "Re-opened after an initial complete pass; stack self-representation is operational but requires further closure on durability and cross-column structure.")
        (mission :id M-three-column-stack :summary "In ARGUE phase; formalizes three coordinated columns (math, project, code) with machine-checkable cross-column invariants.")
        (mission :id M-futon-enrichment :summary "In INSTANTIATE phase; layered rational reconstruction is live-tested and now needs API/browser wiring to expose cross-column provenance in Arxana.")
      ))
    (devmap :id futon5
      :summary "FUTON5 builds and collects general-purpose design patterns for improvisation, with several demonstrator instances."
      :missions (
        (mission :id M-diagram-composition :summary "Extended `ct/mission.clj` to validate composed multi-diagram systems with shared constraints (futon3 timescale stack validated).")
        (mission :id M-pattern-exotype-bridge :summary "Embedded 791 futon3 patterns into 8-bit exotype space via hexagram-anchored regression, enabling executable cross-domain mapping.")
        (mission :id M-sci-detection-pipeline :summary "Built an 8-component SCI detector for MMCA runs to classify Wolfram classes from spacetime/particle/information dynamics.")
      ))
    (devmap :id futon6
      :summary "FUTON6 is a comprehensive mathematics dictionary where informal and formal arguments coexist, indexed by patterns at multiple levels of abstraction."
      :missions ())
    (devmap :id futon7
      :summary "FUTON7 is a new form of knowledge economy that adds transparency to the regular economy by tracking costs, relationships, and externalities that current systems obscure."
      :missions ())
  ))
)
