%%{init: { 'themeVariables': { 'fontSize': '26px', 'labelTextSize': '24px' } }}%%
graph LR
  f0["Futon 0 — FUTON0 Development Map — Human-System Interface"]
  f1["Futon 1 — FUTON1 Development Map — Deterministic Storage Substrate"]
  f2["Futon 2 — FUTON2 Development Map — Active Inference Engine & Ant Demonstrators"]
  f3["Futon 3 — FUTON3 Development Map — Flexiformal Proofwork & Pattern Checking"]
  f4["Futon 4 — FUTON4 Development Map — Memory Atelier & Hypertext Editing"]
  f5["Futon 5 — FUTON5 Development Map — Design Patterns for Improvisation"]
  f6["Futon 6 — FUTON6 Development Map — Comprehensive Mathematics Dictionary"]
  f7["Futon 7 — FUTON7 Development Map — Transparent Knowledge Economy"]
  f0 -->|P0| f1
  f1 -->|P8| f2
  f1 -->|P0,P7,context| f3
  f1 -->|P8| f5
  f2 -->|P4,P9,context| f1
  f2 -->|P10,P12,P2,…| f3
  f2 -->|P2,P6| f4
  f2 -->|P7,context| f5
  f2 -->|P12| f7
  f3 -->|P8,context| f0
  f3 -->|P1,P11,P2,…| f1
  f3 -->|P2,P9,context| f2
  f3 -->|P11,P3,P7| f4
  f3 -->|P10| f6
  f4 -->|P1,P4,P5| f1
  f5 -->|P4,context| f2
  f5 -->|P2| f3
