;;; fubar-test.el --- ERT tests for fubar -*- lexical-binding: t; -*-

(require 'cl-lib)
(require 'ert)
(require 'subr-x)

(defconst fubar--test-root
  (expand-file-name "../.." (file-name-directory (or load-file-name buffer-file-name))))

(add-to-list 'load-path (expand-file-name "contrib" fubar--test-root))

(require 'fubar)

(defun fubar--read-events (path)
  (with-temp-buffer
    (insert-file-contents path)
    (goto-char (point-min))
    (read (current-buffer))))

(ert-deftest fubar-log-event-writes-edn ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint nil))
          (my-fubar-log-event "fubar-1" :pattern/used (list :pattern/id "p1"))
          (let* ((events (fubar--read-events file))
                 (event (aref events 0)))
            (should (= 1 (length events)))
            (should (equal "fubar-1" (plist-get event :event/session)))
            (should (eq :pattern/used (plist-get event :event/type)))))
      (when (file-exists-p file)
        (delete-file file)))))

(ert-deftest fubar-log-clock-in-event ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint nil))
          (my-fubar-log-clock-in "fubar-2" "pattern/a" "intent")
          (let* ((events (fubar--read-events file))
                 (event (aref events 0)))
            (should (= 1 (length events)))
            (should (eq :clock-in/start (plist-get event :event/type)))
            (should (equal "pattern/a" (plist-get event :clock-in/pattern-id)))
            (should (equal "intent" (plist-get event :clock-in/intent)))))
      (when (file-exists-p file)
        (delete-file file)))))

(ert-deftest fubar-log-clock-out-event ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint nil))
          (my-fubar-log-clock-out "fubar-3" (list :session/status :success))
          (let* ((events (fubar--read-events file))
                 (event (aref events 0)))
            (should (= 1 (length events)))
            (should (eq :clock-out/complete (plist-get event :event/type)))
            (should (equal "fubar-3" (plist-get event :event/session)))))
      (when (file-exists-p file)
        (delete-file file)))))

(ert-deftest fubar-log-doc-written-event ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint nil))
          (my-fubar-log-doc-written "fubar-5" (list :path "docs/demo.md"))
          (let* ((events (fubar--read-events file))
                 (event (aref events 0)))
            (should (= 1 (length events)))
            (should (eq :doc/written (plist-get event :event/type)))
            (should (equal "docs/demo.md" (plist-get event :path)))))
      (when (file-exists-p file)
        (delete-file file)))))

(ert-deftest fubar-load-events-reads-log ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint nil))
          (my-fubar-log-event "fubar-4" :pattern/used (list :pattern/id "p2"))
          (let* ((events (my-fubar-load-events))
                 (event (aref events 0)))
            (should (= 1 (length events)))
            (should (eq :pattern/used (plist-get event :event/type)))))
      (when (file-exists-p file)
        (delete-file file)))))

(ert-deftest fubar-record-artifact-updates-session ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint nil))
          (my-fubar-record-artifact "fubar-6" "docs/demo.md" :created)
          (let* ((session (my-fubar-get-session "fubar-6"))
                 (artifacts (plist-get session :artifacts))
                 (stats (plist-get session :stats)))
            (should (= 1 (length artifacts)))
            (should (= 1 (plist-get stats :artifacts)))))
      (when (file-exists-p file)
        (delete-file file)))))

(ert-deftest fubar-society-paper-in-clock-out ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint nil))
          (my-fubar-log-pattern-used "fubar-7" "pattern/x" "dep")
          (my-fubar-log-doc-written "fubar-7" (list :path "docs/demo.md"))
          (my-fubar-record-artifact "fubar-7" "docs/demo.md")
          (my-fubar-set-society-paper "fubar-7" "summary")
          (my-fubar-log-clock-out "fubar-7" (list :session/status :success))
          (let* ((events (fubar--read-events file))
                 (event (aref events (1- (length events)))))
            (should (eq :clock-out/complete (plist-get event :event/type)))
            (should (equal "summary" (plist-get event :society-paper)))
            (should (= 1 (length (plist-get event :pattern/trail))))
            (should (= 1 (length (plist-get event :docs-written))))
            (should (= 1 (length (plist-get event :artifacts))))))
      (when (file-exists-p file)
        (delete-file file)))))

(ert-deftest fubar-stats-update-for-events ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint nil))
          (my-fubar-log-pattern-used "fubar-8" "pattern/y")
          (my-fubar-log-doc-written "fubar-8" (list :path "docs/demo.md"))
          (my-fubar-record-artifact "fubar-8" "docs/demo.md")
          (let* ((session (my-fubar-get-session "fubar-8"))
                 (stats (plist-get session :stats)))
            (should (= 2 (plist-get stats :events)))
            (should (= 1 (plist-get stats :patterns-used)))
            (should (= 1 (plist-get stats :docs-written)))
            (should (= 1 (plist-get stats :artifacts)))))
      (when (file-exists-p file)
        (delete-file file)))))

(ert-deftest fubar-falls-back-to-edn-when-post-fails ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint "http://localhost:9999"))
          (cl-letf (((symbol-function 'my-fubar--post-event) (lambda (_event) nil)))
            (my-fubar-log-event "fubar-2" :doc/written (list :doc/path "docs/demo.md")))
          (let* ((events (fubar--read-events file))
                 (event (aref events 0)))
            (should (= 1 (length events)))
            (should (eq :doc/written (plist-get event :event/type)))))
      (when (file-exists-p file)
        (delete-file file)))))

(ert-deftest fubar-post-success-skips-edn ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint "http://localhost:9999")
              (appended nil))
          (cl-letf (((symbol-function 'my-fubar--post-event) (lambda (_event) t))
                    ((symbol-function 'my-fubar--append-event)
                     (lambda (_event) (setq appended t))))
            (my-fubar-log-event "fubar-5" :pattern/used (list :pattern/id "p3")))
          (should (not appended)))
      (when (file-exists-p file)
        (delete-file file)))))

(ert-deftest fubar-session-id-latches-and-clears ()
  (let ((file (make-temp-file "fubar-log")))
    (unwind-protect
        (let ((my-fubar-edn-log-file file)
              (my-fubar-fulab-endpoint nil)
              (my-fubar-session-id-fn (lambda () "from-fn")))
          (should (equal "from-fn" (my-fubar-session-id)))
          (my-fubar-log-clock-in "fubar-latch" "pattern/a" "intent")
          (should (equal "fubar-latch" (my-fubar-session-id)))
          (my-fubar-log-clock-out "fubar-latch" (list :session/status :success))
          (should (equal "from-fn" (my-fubar-session-id))))
      (when (file-exists-p file)
        (delete-file file)))))
