#!/usr/bin/env python3
"""Generate a concise FUTON stack argument as an s-expression.

Inputs:
- holes/futon*.devmap (one-line devmap summaries via @IFR and mission mentions)
- holes/completed-mission-summaries.md
- holes/non-completed-mission-summaries.md

Output:
- holes/holistic-argument-sketch.sexp (by default)
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HOLES = ROOT / "holes"
DEFAULT_OUT = HOLES / "holistic-argument-sketch.sexp"
MISSION_SUMMARY_FILES = [
    HOLES / "completed-mission-summaries.md",
    HOLES / "non-completed-mission-summaries.md",
]


MISSION_ID_RE = re.compile(r"(?<![A-Za-z0-9-])(M-[a-z0-9-]+)(?![A-Za-z0-9-])")


def normalize_space(text: str) -> str:
    return " ".join(text.strip().split())


def lisp_quote(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def devmap_sort_key(path: Path) -> tuple[int, str]:
    stem = path.stem  # e.g. futon3a
    suffix = stem.removeprefix("futon")
    match = re.match(r"^(\d+)([a-z]*)$", suffix)
    if not match:
        return (999, suffix)
    number = int(match.group(1))
    tail = match.group(2)
    return (number, tail)


def parse_ifr_summary(devmap_text: str) -> str:
    lines = devmap_text.splitlines()
    for idx, line in enumerate(lines):
        if line.startswith("@IFR:"):
            parts = [line[len("@IFR:") :].strip()]
            for follow in lines[idx + 1 :]:
                stripped = follow.strip()
                if not stripped:
                    continue
                if stripped.startswith("@") or stripped.startswith("##") or stripped.startswith("! "):
                    break
                parts.append(stripped)
            summary = normalize_space(" ".join(parts))
            if summary:
                return summary
    return "(missing @IFR summary)"


def parse_mission_summaries(paths: list[Path]) -> dict[str, str]:
    summaries: dict[str, str] = {}
    for path in paths:
        if not path.exists():
            continue
        for raw_line in path.read_text().splitlines():
            line = raw_line.strip()
            if not line.startswith("- `M-"):
                continue
            try:
                mission_id = line.split("`", 2)[1]
            except IndexError:
                continue
            after_id = line.split("`", 2)[2].strip()
            after_id = re.sub(r"^[—-]\s*", "", after_id)
            if "(Devmap:" in after_id:
                summary = after_id.split("(Devmap:", 1)[0].strip()
            else:
                summary = after_id.strip()
            if summary:
                summaries[mission_id] = normalize_space(summary)
    return summaries


def parse_missions_from_devmap(devmap_text: str) -> list[str]:
    missions: list[str] = []
    for mission_id in MISSION_ID_RE.findall(devmap_text):
        if mission_id not in missions:
            missions.append(mission_id)
    return missions


def build_argument(out_path: Path) -> str:
    mission_summaries = parse_mission_summaries(MISSION_SUMMARY_FILES)
    devmap_paths = sorted(HOLES.glob("futon*.devmap"), key=devmap_sort_key)

    lines: list[str] = []
    lines.append("; Generated by scripts/generate_holistic_argument_sexp.py")
    lines.append("(holistic-argument")
    lines.append(
        "  (thesis "
        + lisp_quote(
            "FUTON is a self-representing stack that links aspiration (devmaps), execution (missions), and evidence into an auditable argument for what to do next."
        )
        + ")"
    )
    lines.append("  (devmaps")

    for devmap_path in devmap_paths:
        devmap_id = devmap_path.stem
        devmap_text = devmap_path.read_text()
        summary = parse_ifr_summary(devmap_text)
        missions = parse_missions_from_devmap(devmap_text)

        lines.append(f"    (devmap :id {devmap_id}")
        lines.append(f"      :summary {lisp_quote(summary)}")
        if missions:
            lines.append("      :missions (")
            for mission_id in missions:
                mission_summary = mission_summaries.get(
                    mission_id, "Summary missing in mission summary index."
                )
                lines.append(
                    f"        (mission :id {mission_id} :summary {lisp_quote(mission_summary)})"
                )
            lines.append("      ))")
        else:
            lines.append("      :missions ())")

    lines.append("  ))")
    lines.append(")")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        default=str(DEFAULT_OUT),
        help="Output .sexp path (default: holes/holistic-argument-sketch.sexp).",
    )
    args = parser.parse_args()

    out_path = Path(args.out).resolve()
    content = build_argument(out_path)
    out_path.write_text(content)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
